backend:
    name: github
    repo: thumbtack/thumbprint
    open_authoring: true

publish_mode: editorial_workflow

media_folder: www/static/img
public_folder: /img

# Changes here should also be made in `createPages` within `gatsby-node.js`. Eventually, we'll be
# able to keep the files in `www/src/pages` and use as the collection folder. That means that we
# won't need the code in `gatsby-node.js`. This is the downstream issue:
# https://github.com/netlify/netlify-cms/issues/513
collections:
    - name: 'components-usage'
      label: 'Components (Usage)'
      folder: 'www/src/cms/components-usage'
      create: true
      slug: '{{slug}}'
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
    - name: 'components-ios'
      label: 'Components (iOS)'
      folder: 'www/src/cms/components-ios'
      create: true
      slug: '{{slug}}'
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
    - name: 'components-android'
      label: 'Components (Android)'
      folder: 'www/src/cms/components-android'
      create: true
      slug: '{{slug}}'
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
